import type { Opportunity } from "@/features/opportunities/types";

export const demoOpportunities = [
  {
    id: "opp-youth-digital-skills-fellowship",
    title: "Youth Digital Skills Fellowship",
    organization: "Kabul Future Lab",
    category: "training-program",
    location: "Kabul",
    country: "Afghanistan",
    workMode: "hybrid",
    employmentType: "fellowship",
    deadline: "2026-08-22T23:59:00Z",
    description:
      "A fictional 10-week fellowship introducing Afghan youth to web basics, online collaboration, and career planning.",
    requirements: [
      "Age 18-28",
      "Basic computer literacy",
      "Available for weekly in-person workshops",
    ],
    applyLink: "https://example.test/apply/youth-digital-skills",
    tags: ["digital-skills", "career-readiness", "youth"],
    featured: true,
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-11T09:00:00Z",
  },
  {
    id: "opp-remote-junior-data-assistant",
    title: "Remote Junior Data Assistant",
    organization: "Horizon Research Collective",
    category: "remote-work",
    location: "Online",
    country: "Remote",
    workMode: "remote",
    employmentType: "contract",
    deadline: "2026-08-28T23:59:00Z",
    description:
      "A fictional remote role supporting spreadsheet cleanup, survey tagging, and simple research summaries.",
    requirements: [
      "Strong attention to detail",
      "Comfortable with spreadsheets",
      "Reliable internet connection",
    ],
    applyLink: "https://example.test/apply/remote-data-assistant",
    tags: ["data", "remote", "entry-level"],
    featured: false,
    createdAt: "2026-08-09T08:30:00Z",
    updatedAt: "2026-08-09T08:30:00Z",
  },
  {
    id: "opp-women-in-stem-scholarship",
    title: "Women in STEM Scholarship",
    organization: "Bright Path Education Fund",
    category: "scholarship",
    location: "Herat",
    country: "Afghanistan",
    workMode: "onsite",
    employmentType: "not-applicable",
    deadline: "2026-12-01T23:59:00Z",
    description:
      "A fictional scholarship for young women pursuing science, technology, engineering, or mathematics studies.",
    requirements: [
      "High school transcript",
      "Personal statement",
      "Proof of admission or application",
    ],
    applyLink: "https://example.test/apply/women-stem-scholarship",
    tags: ["scholarship", "stem", "women"],
    featured: true,
    createdAt: "2026-07-30T10:00:00Z",
    updatedAt: "2026-08-02T11:30:00Z",
  },
  {
    id: "opp-community-health-volunteer",
    title: "Community Health Volunteer",
    organization: "Neighborhood Care Initiative",
    category: "volunteer-work",
    location: "Mazar-i-Sharif",
    country: "Afghanistan",
    workMode: "onsite",
    employmentType: "not-applicable",
    deadline: "2026-09-30T23:59:00Z",
    description:
      "A fictional volunteer opportunity supporting health awareness sessions for youth and families.",
    requirements: [
      "Interest in public health",
      "Dari or Pashto communication skills",
      "Available two afternoons per week",
    ],
    applyLink: "https://example.test/apply/community-health-volunteer",
    tags: ["health", "volunteer", "community"],
    featured: false,
    createdAt: "2026-08-01T12:00:00Z",
    updatedAt: "2026-08-03T12:00:00Z",
  },
  {
    id: "opp-frontend-web-development-internship",
    title: "Frontend Web Development Internship",
    organization: "CodeBridge Studio",
    category: "internship",
    location: "Online",
    country: "Remote",
    workMode: "remote",
    employmentType: "part-time",
    deadline: "2026-10-28T23:59:00Z",
    description:
      "A fictional internship for beginners interested in React, accessibility, and portfolio projects.",
    requirements: [
      "Basic HTML and CSS knowledge",
      "One small coding sample",
      "Availability for mentor check-ins",
    ],
    applyLink: "https://example.test/apply/frontend-internship",
    tags: ["frontend", "react", "internship"],
    featured: true,
    createdAt: "2026-08-12T14:15:00Z",
    updatedAt: "2026-08-12T14:15:00Z",
  },
  {
    id: "opp-english-career-readiness-course",
    title: "English for Career Readiness Course",
    organization: "Global Learning Rooms",
    category: "online-course",
    location: "Online",
    country: "Remote",
    workMode: "remote",
    employmentType: "not-applicable",
    deadline: "2027-01-10T23:59:00Z",
    description:
      "A fictional online course focused on CV writing, interview vocabulary, and workplace communication.",
    requirements: [
      "Beginner English level",
      "Mobile or computer access",
      "Commitment to weekly practice",
    ],
    applyLink: "https://example.test/apply/english-career-course",
    tags: ["english", "career", "online-course"],
    featured: false,
    createdAt: "2026-07-20T07:45:00Z",
    updatedAt: "2026-07-22T07:45:00Z",
  },
  {
    id: "opp-agriculture-innovation-trainee",
    title: "Agriculture Innovation Trainee",
    organization: "Green Valley Skills Center",
    category: "training-program",
    location: "Bamyan",
    country: "Afghanistan",
    workMode: "onsite",
    employmentType: "temporary",
    deadline: "2026-11-20T23:59:00Z",
    description:
      "A fictional hands-on program covering greenhouse basics, irrigation planning, and small farm business skills.",
    requirements: [
      "Interest in agriculture",
      "Able to attend practical sessions",
      "No previous experience required",
    ],
    applyLink: "https://example.test/apply/agriculture-trainee",
    tags: ["agriculture", "training", "rural-youth"],
    featured: false,
    createdAt: "2026-07-26T13:00:00Z",
    updatedAt: "2026-07-28T13:00:00Z",
  },
  {
    id: "opp-junior-communications-officer",
    title: "Junior Communications Officer",
    organization: "New Voices Media Hub",
    category: "job",
    location: "Kandahar",
    country: "Afghanistan",
    workMode: "hybrid",
    employmentType: "full-time",
    deadline: "2026-08-20T23:59:00Z",
    description:
      "A fictional entry-level communications role supporting newsletters, social posts, and event updates.",
    requirements: [
      "Strong writing skills",
      "Experience with social media tools",
      "Dari and Pashto preferred",
    ],
    applyLink: "https://example.test/apply/junior-communications",
    tags: ["communications", "media", "job"],
    featured: true,
    createdAt: "2026-08-13T09:20:00Z",
    updatedAt: "2026-08-13T09:20:00Z",
  },
  {
    id: "opp-regional-peacebuilding-workshop",
    title: "Regional Peacebuilding Workshop",
    organization: "Youth Dialogue Network",
    category: "training-program",
    location: "Dushanbe",
    country: "Tajikistan",
    workMode: "onsite",
    employmentType: "temporary",
    deadline: "2026-12-12T23:59:00Z",
    description:
      "A fictional regional workshop for young community leaders interested in dialogue and conflict resolution.",
    requirements: [
      "Age 20-30",
      "Community project experience",
      "Valid travel document",
    ],
    applyLink: "https://example.test/apply/peacebuilding-workshop",
    tags: ["leadership", "peacebuilding", "regional"],
    featured: false,
    createdAt: "2026-07-19T10:30:00Z",
    updatedAt: "2026-07-24T10:30:00Z",
  },
  {
    id: "opp-undergraduate-access-grant",
    title: "Undergraduate Access Grant",
    organization: "Step Forward Scholars",
    category: "scholarship",
    location: "Islamabad",
    country: "Pakistan",
    workMode: "hybrid",
    employmentType: "not-applicable",
    deadline: "2027-02-01T23:59:00Z",
    description:
      "A fictional grant supporting Afghan students applying to undergraduate programs in the region.",
    requirements: [
      "Academic records",
      "Financial need statement",
      "Two references",
    ],
    applyLink: "https://example.test/apply/undergraduate-access-grant",
    tags: ["scholarship", "undergraduate", "regional"],
    featured: false,
    createdAt: "2026-08-05T11:00:00Z",
    updatedAt: "2026-08-06T11:00:00Z",
  },
  {
    id: "opp-small-business-operations-assistant",
    title: "Small Business Operations Assistant",
    organization: "MarketLink Services",
    category: "job",
    location: "Jalalabad",
    country: "Afghanistan",
    workMode: "onsite",
    employmentType: "full-time",
    deadline: "2026-09-25T23:59:00Z",
    description:
      "A fictional operations role helping a small business team with inventory records and customer coordination.",
    requirements: [
      "Basic accounting knowledge",
      "Customer service mindset",
      "Comfortable using office software",
    ],
    applyLink: "https://example.test/apply/operations-assistant",
    tags: ["business", "operations", "entry-level"],
    featured: false,
    createdAt: "2026-08-07T15:00:00Z",
    updatedAt: "2026-08-07T15:00:00Z",
  },
  {
    id: "opp-climate-storytelling-micro-grant",
    title: "Climate Storytelling Micro-Grant",
    organization: "Open Lens Youth Fund",
    category: "volunteer-work",
    location: "Online",
    country: "Remote",
    workMode: "remote",
    employmentType: "fellowship",
    deadline: "2026-08-29T23:59:00Z",
    description:
      "A fictional micro-grant for youth teams producing short digital stories about climate resilience.",
    requirements: [
      "Team of two to four youth",
      "Short project proposal",
      "Sample photo, audio, or video work",
    ],
    applyLink: "https://example.test/apply/climate-storytelling",
    tags: ["climate", "storytelling", "grant"],
    featured: true,
    createdAt: "2026-08-14T16:45:00Z",
    updatedAt: "2026-08-14T16:45:00Z",
  },
] satisfies Opportunity[];
